default_platform(:ios)

platform :ios do

  desc "Build & upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "testXcBuild",
      export_method: "app-store"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Distribute to Firebase"
  lane :firebase do
    build_app(
      scheme: "testXcBuild",
      export_method: "ad-hoc"
    )

    firebase_app_distribution(
      app: "testxcbuild",
      testers: "25umariarina@gmail.com"
    )
  end

end